["pyproject.toml".tool.black]
line-length = 120

["pyproject.toml".tool.poetry.dev-dependencies]
flake8 = "*"
black = "*"
mypy = "*"
nitpick = "*"
pre-commit = "*"

["setup.cfg".flake8]
ignore = "W0622,D100,D104,D107,D202,D203,D401,W503"
max-line-complexity = 21
inline-quotes = "double"
max-line-length = 120

["setup.cfg".isort]
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "tests"
line_length = 120
multi_line_output = 3
skip = ".tox,build"
force_single_line = true

["setup.cfg".mypy]
follow_imports = "skip"
ignore_missing_imports = false
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true
