["pyproject.toml".tool.black]
line-length = 120

["pyproject.toml".tool.poetry.dev-dependencies]
flake8 = "*"
black = "*"
mypy = "*"
nitpick = "*"
pre-commit = "*"

["setup.cfg".flake8]
ignore = "W0622,D100,D104,D107,D202,D203,D401,W503"
max-line-complexity = 21
inline-quotes = "double"
max-line-length = 120

["setup.cfg".isort]
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "tests"
line_length = 120
multi_line_output = 3
skip = ".tox,build"
force_single_line = true

["setup.cfg".mypy]
follow_imports = "skip"
ignore_missing_imports = false
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true

[nitpick.files.present]
"pyproject.toml" = "Install poetry and run 'poetry init' to create it"

[nitpick.files.present]
".pre-commit-config.yaml" = "Create the file with the contents below, then run 'pre-commit install'"

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions,
          flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill,
          flake8-pytest, flake8-quotes, yesqa]
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
      - id: pyupgrade
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v3.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
"""

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.23.1
    hooks:
      - id: nitpick
"""
