["pyproject.toml".tool.black]
line-length = 120

["pyproject.toml".tool.poetry.dev-dependencies]
flake8 = "*"
black = "*"
mypy = "*"

["setup.cfg".iflake8]
ignore = W0622,D100,D104,D107,D202,D203,D401,W503
max-line-complexity = 21
inline-quotes = double
max-line-length = 120

["setup.cfg".isort]
combine_as_imports = True
force_grid_wrap = 0
include_trailing_comma = True
known_first_party = tests
line_length = 120
multi_line_output = 3
skip = .tox,build
force_single_line = True

["setup.cfg".imypy]
follow_imports = skip
ignore_missing_imports = False
strict_optional = True
warn_no_return = True
warn_redundant_casts = True
warn_unused_ignores = True
